// Code generated by "stringer -type itemType"; DO NOT EDIT

package parser

import "fmt"

const _itemType_name = "itemErroritemSpaceitemFloatitemIntegeritemSymbolitemStringitemDotitemCharLititemCharitemCommentitemEOF"

var _itemType_index = [...]uint8{0, 9, 18, 27, 38, 48, 58, 65, 76, 84, 95, 102}

func (i itemType) String() string {
	i -= 1
	if i < 0 || i >= itemType(len(_itemType_index)-1) {
		return fmt.Sprintf("itemType(%d)", i+1)
	}
	return _itemType_name[_itemType_index[i]:_itemType_index[i+1]]
}
